name: Push to Docker Hub (Docker CLI)

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push 7.1
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/ffmpeg-builds-legacy/n7.1/win64-nonfree-shared-7.1:latest
          docker tag ghcr.io/${{ github.repository_owner }}/ffmpeg-builds-legacy/n7.1/win64-nonfree-shared-7.1:latest ${{ secrets.DOCKERHUB_USERNAME }}/ffmpeg-win64-nonfree-shared-7.1:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ffmpeg-win64-nonfree-shared-7.1:latest

      - name: Push 8.0
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/ffmpeg-builds-legacy/n8.0/win64-nonfree-shared-8.0:latest
          docker tag ghcr.io/${{ github.repository_owner }}/ffmpeg-builds-legacy/n8.0/win64-nonfree-shared-8.0:latest ${{ secrets.DOCKERHUB_USERNAME }}/ffmpeg-win64-nonfree-shared-8.0:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ffmpeg-win64-nonfree-shared-8.0:latest
